import { QueryBuilder } from "../../QueryBuilder/QueryBuilder";
import { IIndexMetaData } from "../../MetaData/Interface/IIndexMetaData";
import { IQueryCommand } from "../../QueryBuilder/Interface/IQueryCommand";
import { IObjectType } from "../../Common/Type";
import { IColumnTypeDefaults } from "../../Common/IColumnTypeDefaults";

export class MysqlQueryBuilder extends QueryBuilder {
    public supportedColumnTypes: Map<"number" | "boolean" | "int" | "tinyint" | "smallint" | "mediumint" | "bigint" | "int2" | "int4" | "int8" | "integer" | "unsigned big int" | "float" | "float4" | "float8" | "double" | "dec" | "decimal" | "numeric" | "real" | "double precision" | "smallmoney" | "money" | "datetime" | "datetime2" | "smalldatetime" | "date" | "datetimeoffset" | "interval year" | "interval day" | "interval" | "year" | "time" | "time with time zone" | "time without time zone" | "timestamp" | "timestamp without time zone" | "timestamp with time zone" | "timestamp with local time zone" | "binary" | "varbinary" | "tinyblob" | "mediumblob" | "blob" | "longblob" | "bytea" | "long" | "raw" | "long raw" | "bfile" | "clob" | "nclob" | "image" | "character varying" | "varying character" | "nvarchar" | "character" | "native character" | "varchar" | "char" | "nchar" | "varchar2" | "nvarchar2" | "tinytext" | "mediumtext" | "text" | "ntext" | "longtext" | "citext" | "bit" | "bool" | "point" | "line" | "lseg" | "box" | "circle" | "path" | "polygon" | "uuid" | "uniqueidentifier" | "xml" | "json" | "jsonb" | "enum" | "rowid" | "urowid" | "cidr" | "inet" | "macaddr" | "bit varying" | "varbit" | "tsvector" | "tsquery" | "cursor" | "hierarchyid" | "sql_variant" | "table", "String" | "Boolean" | "Numeric" | "Decimal" | "Binary" | "DataString" | "Date" | "Time" | "Enum" | "Identifier" | "Timestamp">;
    public columnTypesWithOption: ("number" | "boolean" | "int" | "tinyint" | "smallint" | "mediumint" | "bigint" | "int2" | "int4" | "int8" | "integer" | "unsigned big int" | "float" | "float4" | "float8" | "double" | "dec" | "decimal" | "numeric" | "real" | "double precision" | "smallmoney" | "money" | "datetime" | "datetime2" | "smalldatetime" | "date" | "datetimeoffset" | "interval year" | "interval day" | "interval" | "year" | "time" | "time with time zone" | "time without time zone" | "timestamp" | "timestamp without time zone" | "timestamp with time zone" | "timestamp with local time zone" | "binary" | "varbinary" | "tinyblob" | "mediumblob" | "blob" | "longblob" | "bytea" | "long" | "raw" | "long raw" | "bfile" | "clob" | "nclob" | "image" | "character varying" | "varying character" | "nvarchar" | "character" | "native character" | "varchar" | "char" | "nchar" | "varchar2" | "nvarchar2" | "tinytext" | "mediumtext" | "text" | "ntext" | "longtext" | "citext" | "bit" | "bool" | "point" | "line" | "lseg" | "box" | "circle" | "path" | "polygon" | "uuid" | "uniqueidentifier" | "xml" | "json" | "jsonb" | "enum" | "rowid" | "urowid" | "cidr" | "inet" | "macaddr" | "bit varying" | "varbit" | "tsvector" | "tsquery" | "cursor" | "hierarchyid" | "sql_variant" | "table")[];
    public columnTypeDefaults: Map<"number" | "boolean" | "int" | "tinyint" | "smallint" | "mediumint" | "bigint" | "int2" | "int4" | "int8" | "integer" | "unsigned big int" | "float" | "float4" | "float8" | "double" | "dec" | "decimal" | "numeric" | "real" | "double precision" | "smallmoney" | "money" | "datetime" | "datetime2" | "smalldatetime" | "date" | "datetimeoffset" | "interval year" | "interval day" | "interval" | "year" | "time" | "time with time zone" | "time without time zone" | "timestamp" | "timestamp without time zone" | "timestamp with time zone" | "timestamp with local time zone" | "binary" | "varbinary" | "tinyblob" | "mediumblob" | "blob" | "longblob" | "bytea" | "long" | "raw" | "long raw" | "bfile" | "clob" | "nclob" | "image" | "character varying" | "varying character" | "nvarchar" | "character" | "native character" | "varchar" | "char" | "nchar" | "varchar2" | "nvarchar2" | "tinytext" | "mediumtext" | "text" | "ntext" | "longtext" | "citext" | "bit" | "bool" | "point" | "line" | "lseg" | "box" | "circle" | "path" | "polygon" | "uuid" | "uniqueidentifier" | "xml" | "json" | "jsonb" | "enum" | "rowid" | "urowid" | "cidr" | "inet" | "macaddr" | "bit varying" | "varbit" | "tsvector" | "tsquery" | "cursor" | "hierarchyid" | "sql_variant" | "table", IColumnTypeDefaults>;
    public columnTypeMap: Map<"number" | "boolean" | "int" | "tinyint" | "smallint" | "mediumint" | "bigint" | "int2" | "int4" | "int8" | "integer" | "unsigned big int" | "float" | "float4" | "float8" | "double" | "dec" | "decimal" | "numeric" | "real" | "double precision" | "smallmoney" | "money" | "datetime" | "datetime2" | "smalldatetime" | "date" | "datetimeoffset" | "interval year" | "interval day" | "interval" | "year" | "time" | "time with time zone" | "time without time zone" | "timestamp" | "timestamp without time zone" | "timestamp with time zone" | "timestamp with local time zone" | "binary" | "varbinary" | "tinyblob" | "mediumblob" | "blob" | "longblob" | "bytea" | "long" | "raw" | "long raw" | "bfile" | "clob" | "nclob" | "image" | "character varying" | "varying character" | "nvarchar" | "character" | "native character" | "varchar" | "char" | "nchar" | "varchar2" | "nvarchar2" | "tinytext" | "mediumtext" | "text" | "ntext" | "longtext" | "citext" | "bit" | "bool" | "point" | "line" | "lseg" | "box" | "circle" | "path" | "polygon" | "uuid" | "uniqueidentifier" | "xml" | "json" | "jsonb" | "enum" | "rowid" | "urowid" | "cidr" | "inet" | "macaddr" | "bit varying" | "varbit" | "tsvector" | "tsquery" | "cursor" | "hierarchyid" | "sql_variant" | "table" | "defaultString" | "defaultNumberic" | "defaultDecimal" | "defaultBoolean" | "defaultBinary" | "defaultDataString" | "defaultDate" | "defaultTime" | "defaultEnum" | "defaultIdentifier" | "defaultTimestamp", "number" | "boolean" | "int" | "tinyint" | "smallint" | "mediumint" | "bigint" | "int2" | "int4" | "int8" | "integer" | "unsigned big int" | "float" | "float4" | "float8" | "double" | "dec" | "decimal" | "numeric" | "real" | "double precision" | "smallmoney" | "money" | "datetime" | "datetime2" | "smalldatetime" | "date" | "datetimeoffset" | "interval year" | "interval day" | "interval" | "year" | "time" | "time with time zone" | "time without time zone" | "timestamp" | "timestamp without time zone" | "timestamp with time zone" | "timestamp with local time zone" | "binary" | "varbinary" | "tinyblob" | "mediumblob" | "blob" | "longblob" | "bytea" | "long" | "raw" | "long raw" | "bfile" | "clob" | "nclob" | "image" | "character varying" | "varying character" | "nvarchar" | "character" | "native character" | "varchar" | "char" | "nchar" | "varchar2" | "nvarchar2" | "tinytext" | "mediumtext" | "text" | "ntext" | "longtext" | "citext" | "bit" | "bool" | "point" | "line" | "lseg" | "box" | "circle" | "path" | "polygon" | "uuid" | "uniqueidentifier" | "xml" | "json" | "jsonb" | "enum" | "rowid" | "urowid" | "cidr" | "inet" | "macaddr" | "bit varying" | "varbit" | "tsvector" | "tsquery" | "cursor" | "hierarchyid" | "sql_variant" | "table">;
    public valueTypeMap: Map<IObjectType<any> | ((...value: any[]) => any), "number" | "boolean" | "int" | "tinyint" | "smallint" | "mediumint" | "bigint" | "int2" | "int4" | "int8" | "integer" | "unsigned big int" | "float" | "float4" | "float8" | "double" | "dec" | "decimal" | "numeric" | "real" | "double precision" | "smallmoney" | "money" | "datetime" | "datetime2" | "smalldatetime" | "date" | "datetimeoffset" | "interval year" | "interval day" | "interval" | "year" | "time" | "time with time zone" | "time without time zone" | "timestamp" | "timestamp without time zone" | "timestamp with time zone" | "timestamp with local time zone" | "binary" | "varbinary" | "tinyblob" | "mediumblob" | "blob" | "longblob" | "bytea" | "long" | "raw" | "long raw" | "bfile" | "clob" | "nclob" | "image" | "character varying" | "varying character" | "nvarchar" | "character" | "native character" | "varchar" | "char" | "nchar" | "varchar2" | "nvarchar2" | "tinytext" | "mediumtext" | "text" | "ntext" | "longtext" | "citext" | "bit" | "bool" | "point" | "line" | "lseg" | "box" | "circle" | "path" | "polygon" | "uuid" | "uniqueidentifier" | "xml" | "json" | "jsonb" | "enum" | "rowid" | "urowid" | "cidr" | "inet" | "macaddr" | "bit varying" | "varbit" | "tsvector" | "tsquery" | "cursor" | "hierarchyid" | "sql_variant" | "table">;
    
    public dropIndexQuery(indexMeta: IIndexMetaData): IQueryCommand[] {
        const query = `ALTER TABLE ${this.entityName(indexMeta.entity)} DROP INDEX ${indexMeta.name}`;
        return [{ query }];
    }
}
