import { IMethodMeta } from "./IMethodMeta";

export const stringMethods: IMethodMeta[] = [
    { name: "charAt", returnType: String, isSupported: true },
    { name: "charCodeAt", returnType: Number, isSupported: true },
    { name: "codePointAt", returnType: Number, isSupported: true },
    { name: "concat", returnType: String, isSupported: true },
    { name: "endsWith", returnType: Boolean, isSupported: true },
    { name: "includes", returnType: Boolean, isSupported: true },
    { name: "indexOf", returnType: Number, isSupported: true },
    { name: "lastIndexOf", returnType: Number, isSupported: true },
    { name: "like", returnType: Boolean, isSupported: true },

    { name: "localeCompare", returnType: Number, isSupported: false },
    { name: "normalize", returnType: String, isSupported: false },

    { name: "repeat", returnType: String, isSupported: true },
    { name: "replace", returnType: String, isSupported: true },
    { name: "slice", returnType: String, isSupported: true },
    { name: "small", returnType: String, isSupported: true },
    { name: "split", returnType: String, isSupported: true },
    { name: "strike", returnType: String, isSupported: true },
    { name: "sub", returnType: String, isSupported: true },
    { name: "substr", returnType: String, isSupported: true },
    { name: "substring", returnType: String, isSupported: true },
    { name: "sup", returnType: String, isSupported: true },
    { name: "startsWith", returnType: String, isSupported: true },
    { name: "toString", returnType: String, isSupported: true },
    { name: "trim", returnType: String, isSupported: true },
    { name: "trimLeft", returnType: String, isSupported: true },
    { name: "trimRight", returnType: String, isSupported: true },
    { name: "toLowerCase", returnType: String, isSupported: true },
    { name: "toUpperCase", returnType: String, isSupported: true },
    { name: "valueOf", returnType: String, isSupported: true },
    { name: "match", returnType: String, isSupported: true },
    { name: "search", returnType: String, isSupported: true },
    { name: "padStart", returnType: String, isSupported: true },
    { name: "padEnd", returnType: String, isSupported: true },
    { name: "toLocaleLowerCase", returnType: String, isSupported: true },
    { name: "toLocaleUpperCase", returnType: String, isSupported: true },

    { name: "repeat", returnType: Boolean, isSupported: true },
    { name: "replace", returnType: Boolean, isSupported: true },
    { name: "split", returnType: Boolean, isSupported: true },
    { name: "startsWith", returnType: Boolean, isSupported: true },
    { name: "substr", returnType: Boolean, isSupported: true },
    { name: "substring", returnType: Boolean, isSupported: true },
    { name: "toLowerCase", returnType: Boolean, isSupported: true },
    { name: "toLocaleLowerCase", returnType: Boolean, isSupported: true },
    { name: "toUpperCase", returnType: Boolean, isSupported: true },
    { name: "toLocaleUpperCase", returnType: Boolean, isSupported: true },
    { name: "toString", returnType: Boolean, isSupported: true },
    { name: "valueOf", returnType: Boolean, isSupported: true },
    { name: "trim", returnType: Boolean, isSupported: true },
];
